//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStoreAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public string LoginName { get; set; }
        public string Pass { get; set; }
        public string NameDisplay { get; set; }
        public Nullable<int> test { get; set; }
    }
}
