//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStoreAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string UserName { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantities { get; set; }
    }
}
