//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APStoreAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string NameDisplay { get; set; }
        public double Value { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
